/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package deneme;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author admin
 */
public class MalzemeEkrani extends javax.swing.JFrame {
      DefaultTableModel model;
    MalzemeIslemleri islemler =  new MalzemeIslemleri ();
    
    /** Creates new form MalzemeEkrani */
    public MalzemeEkrani() {
        initComponents();
         model=(DefaultTableModel)malzeme_tablosu.getModel();
       malzemeGoruntule();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        malzeme_kategori_adi_alani = new javax.swing.JTextField();
        malzeme_adi_alani = new javax.swing.JTextField();
        malzeme_adet_Alani = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        malzeme_tablosu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        malzeme_ekle = new javax.swing.JButton();
        malzeme_guncelle = new javax.swing.JButton();
        malzeme_sil = new javax.swing.JButton();
        cikis = new javax.swing.JButton();
        arama_cubugu = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        mesaj_yazisi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(210, 237, 243));
        setBounds(new java.awt.Rectangle(600, 250, 0, 0));
        setPreferredSize(new java.awt.Dimension(1020, 720));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Malzeme Kategori :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Malzeme Ad :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Malzeme Adet :");

        malzeme_tablosu.setBackground(new java.awt.Color(204, 204, 255));
        malzeme_tablosu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        malzeme_tablosu.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        malzeme_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Malzeme ID", "Malzeme AD", "Malzeme KATEGORİ", "Malzeme ADET"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        malzeme_tablosu.setGridColor(new java.awt.Color(204, 204, 255));
        malzeme_tablosu.setSelectionBackground(new java.awt.Color(255, 255, 255));
        malzeme_tablosu.setSelectionForeground(new java.awt.Color(0, 0, 0));
        malzeme_tablosu.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        malzeme_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malzeme_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(malzeme_tablosu);
        if (malzeme_tablosu.getColumnModel().getColumnCount() > 0) {
            malzeme_tablosu.getColumnModel().getColumn(0).setResizable(false);
            malzeme_tablosu.getColumnModel().getColumn(1).setResizable(false);
            malzeme_tablosu.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(903, 86));

        malzeme_ekle.setBackground(new java.awt.Color(204, 204, 255));
        malzeme_ekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_material.png"))); // NOI18N
        malzeme_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malzeme_ekleActionPerformed(evt);
            }
        });

        malzeme_guncelle.setBackground(new java.awt.Color(204, 204, 255));
        malzeme_guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        malzeme_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malzeme_guncelleActionPerformed(evt);
            }
        });

        malzeme_sil.setBackground(new java.awt.Color(204, 204, 255));
        malzeme_sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        malzeme_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malzeme_silActionPerformed(evt);
            }
        });

        cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });

        arama_cubugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arama_cubuguActionPerformed(evt);
            }
        });
        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(malzeme_ekle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(malzeme_guncelle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(malzeme_sil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 7, Short.MAX_VALUE)
                .add(arama_cubugu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 509, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cikis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cikis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(malzeme_sil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(malzeme_guncelle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(malzeme_ekle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(arama_cubugu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mesaj_yazisi.setForeground(new java.awt.Color(0, 102, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(filler1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(70, 70, 70)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 902, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(85, 85, 85)
                        .add(mesaj_yazisi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 780, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(292, 292, 292)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10))
                            .add(layout.createSequentialGroup()
                                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED))
                            .add(layout.createSequentialGroup()
                                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, malzeme_kategori_adi_alani, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(malzeme_adet_Alani, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(malzeme_adi_alani, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(74, 74, 74)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(malzeme_adi_alani, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(malzeme_kategori_adi_alani, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(malzeme_adet_Alani, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(mesaj_yazisi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 59, Short.MAX_VALUE)
                .add(filler1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        // TODO add your handling code here:
         String ara =arama_cubugu.getText();
        
        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void malzeme_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malzeme_ekleActionPerformed
        // TODO add your handling code here:
         mesaj_yazisi.setText("");
        String malzeme_ad=malzeme_adi_alani.getText();
        String malzeme_kategori=malzeme_kategori_adi_alani.getText();
        String malzeme_adet=malzeme_adet_Alani.getText();
        islemler.malzemeEkle(malzeme_ad,malzeme_kategori,malzeme_adet);
        
        malzemeGoruntule();
        
         mesaj_yazisi.setText("Yeni Malzeme Bilgisi Başarıyla Yüklendi...");
    }//GEN-LAST:event_malzeme_ekleActionPerformed

    private void malzeme_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malzeme_tablosuMouseClicked
        // TODO add your handling code here:
          int selectedrow=malzeme_tablosu.getSelectedRow();
           
        malzeme_adi_alani.setText(model.getValueAt(selectedrow,1).toString());
        malzeme_kategori_adi_alani.setText(model.getValueAt(selectedrow,2).toString());
        malzeme_adet_Alani.setText(model.getValueAt(selectedrow,3).toString());
    }//GEN-LAST:event_malzeme_tablosuMouseClicked

    private void malzeme_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malzeme_guncelleActionPerformed
         // TODO add your handling code here:
         String malzeme_ad = malzeme_adi_alani.getText();
        String malzeme_kategori =  malzeme_kategori_adi_alani.getText();
        String malzeme_adet =  malzeme_adet_Alani.getText();
        
 int selectedrow = malzeme_tablosu.getSelectedRow();
        
        if (selectedrow == -1) {
            
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Malzeme Tablosu şu anda boş. ");
            }
            else {
                mesaj_yazisi.setText("Lütfen güncellenecek bir malzeme bilgisi seçin.");
            }
        }
        else {
            
            
            
            
            int malzeme_id = (int)model.getValueAt(selectedrow,0);
            
            islemler.malzemeGuncelle(malzeme_id,malzeme_ad,malzeme_kategori,malzeme_adet);
            
            malzemeGoruntule();
            
            mesaj_yazisi.setText("Çalışan başarıyla güncellendi...");
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_malzeme_guncelleActionPerformed

    private void malzeme_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malzeme_silActionPerformed
        // TODO add your handling code here:
         mesaj_yazisi.setText("");
       
       
       int selectedrow = malzeme_tablosu.getSelectedRow();
       
       if (selectedrow == -1) {
           if (model.getRowCount() == 0 ) {
               mesaj_yazisi.setText("Malzeme tablosu şu anda boş...");
           }
           else {
               mesaj_yazisi.setText("Lütfen silinecek bir malzeme bilgisi seçin...");
           }
      
       }
       else {
           int malzeme_id = (int)model.getValueAt(selectedrow,0);
           
           islemler.malzemeSil(malzeme_id);
           
       malzemeGoruntule();
           
           mesaj_yazisi.setText("Malzeme başarıyla silindi...");
           
        
       }  
    }//GEN-LAST:event_malzeme_silActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        // TODO add your handling code here
          setVisible(false);
        GirisEkrani geridon=new GirisEkrani();
        geridon.setVisible(true);
    
    }//GEN-LAST:event_cikisActionPerformed

    private void arama_cubuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arama_cubuguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arama_cubuguActionPerformed
 public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        
        malzeme_tablosu.setRowSorter(tr);
        
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
        
    }
   public void malzemeGoruntule(){
        model.setRowCount(0);
         MalzemeIslemleri islem1=new MalzemeIslemleri(); 
        ArrayList<Malzeme> malzemeler = islem1.malzemeGetir();
        if(malzemeler != null){
            for(Malzeme malzeme: malzemeler){
                Object[] eklenecek={malzeme.getMalzeme_id(),malzeme.getMalzeme_ad(), malzeme.getMalzeme_kategori(), malzeme.getMalzeme_adet()};
                model.addRow(eklenecek);
                
            }
            }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MalzemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MalzemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MalzemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MalzemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MalzemeEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JButton cikis;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField malzeme_adet_Alani;
    private javax.swing.JTextField malzeme_adi_alani;
    private javax.swing.JButton malzeme_ekle;
    private javax.swing.JButton malzeme_guncelle;
    private javax.swing.JTextField malzeme_kategori_adi_alani;
    private javax.swing.JButton malzeme_sil;
    private javax.swing.JTable malzeme_tablosu;
    private javax.swing.JLabel mesaj_yazisi;
    // End of variables declaration//GEN-END:variables

}
